services:

1. PostgreSQL Database Service
type: pserv
name: rag-postgres
plan: starter
databaseName: rag_db
user: rag_admin

Allow connections from the web service
ipAllowList:

cidr: 0.0.0.0/0

cidr: 10.0.0.0/8

Define a custom environment variable for Django to use
envVars:

key: DATABASE_URL
fromDatabase:
name: rag-postgres
property: connectionString

2. Django Web Service
type: web
name: rag-chat-app
env: python
buildCommand: "./build.sh"
startCommand: "gunicorn rag_project.wsgi"
plan: starter

Crucial for security and configuration
envVars:

key: PYTHON_VERSION
value: 3.11.8

key: SECRET_KEY
generateValue: true # Render auto-generates a secure key

Reduced from 4 to 2 to prevent "out of memory" (SIGKILL) errors
key: WEB_CONCURRENCY
value: 2

key: GEMINI_API_KEY # REQUIRED: Must be set manually in Render UI as a secret
sync: false

*** MANDATORY FOR CHROMA DB PERSISTENCE ***
This mounts a persistent disk (volume) at the root of your application,
ensuring the "./chroma_db" folder's contents are saved across restarts.
disk:
name: chroma-disk
mountPath: /var/data/chroma
sizeGB: 10 # Starting size for vector storage (can be scaled up)
